name:                ci3661
version:             1
github:              "githubuser/ci3661"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- package.yaml
- stack.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ci3661#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src
  
executables:
  wordle-exe:
    main:                Main.hs
    source-dirs:         wordle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ci3661

  solver-exe:
    main:                Main.hs
    source-dirs:         solver
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ci3661

tests:
  ci3661-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ci3661
